apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- argocd-ingress.yaml
- bmc-reverse-proxy.yaml
- cert-manager.yaml
- external-dns.yaml
- local-pv-provisioner.yaml
- maneki-apps.yaml
- metallb.yaml
- monitoring.yaml
- sandbox.yaml
- secrets.yaml
- teleport.yaml
- rook.yaml
