apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - certificate.yaml
patchesStrategicMerge:
  - deployment.yaml
  - statefulset.yaml
images:
  - name: quay.io/gravitational/teleport-ent
    newName: quay.io/gravitational/teleport
