apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../upstream
  - clusterrolebinding
  - cephblockpool.yaml
  - cephobjectstore.yaml
  - cluster.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
namespace: ceph-hdd
patchesStrategicMerge:
  - operator.yaml
